DELETE FROM RH_STATUS;

INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (7, 'Récupération (Absence)', 'Y', NULL);
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (10, 'Congé maternité', 'Y', NULL);
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (8, 'Congés exceptionnels (Mariage, Deces...)', 'Y', 'CEX');
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (9, 'Congés sans soldes', 'Y', 'CSS');
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (1, 'Présent', 'N', NULL);
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (2, 'Absent', 'Y', NULL);
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (3, 'Congé maladie', 'Y', 'CM');
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (4, 'Congé payé', 'Y', 'CP');
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (5, 'Récupération (Présence)', 'N', NULL);
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (6, 'Heures Supplémentaires', 'N', NULL);
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (11, 'Formation', 'Y', NULL);
INSERT INTO RH_STATUS (ID, LIBELLE, ABSENCE, CODE) VALUES (12, 'Déplacement', 'Y', NULL);
